{
 "title": "Story Dashboard by Let's Node",
 "description": "This dashboard provides a comprehensive overview of the performance and health of the Story Node. It includes key metrics related to block processing times, resource utilization, and system performance, enabling users to monitor the node's efficiency and stability.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$name\"},instance)"
    }
   },
   {
    "name": "name",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$node:(.*)\"},instance)"
    }
   },
   {
    "name": "story_port",
    "label": "Story node port",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "geth_port",
    "label": "Geth Port",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$node:(.*)\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Latest Block Height",
     "type": "stat",
     "description": "The number indicating the most recent block reached by the node's consensus",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_latest_block_height{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "Latest Block Height"
      }
     ]
    },
    {
     "title": "Syncing Status",
     "type": "stat",
     "description": "Shows \"True\" if the node is syncing, \"False\" if not",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_blocksync_syncing{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "Fast Syncing"
      }
     ]
    },
    {
     "title": "Number of Peers",
     "type": "gauge",
     "description": "Tracks the number of connected peers. Too few may indicate connectivity issues, while too many can strain resources. An optimal peer count ensures efficient block propagation and stable network performance",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_p2p_peers{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "Peers"
      }
     ]
    },
    {
     "title": "Validator Uptime Rate",
     "type": "gauge",
     "description": "Calculates the percentage of blocks in which the validator successfully participated without missing any proposals. This metric provides insight into the validator’s performance and reliability in the consensus process. A higher percentage indicates stable and effective participation, while a lower value may signal potential issues such as network disruptions or node overload. Monitoring this rate helps ensure the validator’s optimal performance and the overall health of the network",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (avg(cometbft_consensus_validator_missed_blocks{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"})) / (avg(cometbft_consensus_height{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validator Voting Power",
     "type": "gauge",
     "description": "Measures the percentage of the total validator power held by a specific validator. It is calculated by dividing the average power of the targeted validator by the average total power of all validators and multiplying by 100. This metric helps assess the validator's influence in the consensus process and its relative voting power in the network. Monitoring this share is essential for ensuring balanced participation and detecting potential power centralization risks",
     "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(cometbft_consensus_validator_power{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}) / avg(cometbft_consensus_validators_power{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chain Cumulative Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_consensus_chain_size_bytes{chain_id=\"iliad-0\", job=\"$job\", instance=\"$node:$story_port\"}",
       "legendFormat": "{{chain_id}} Node Latest Block Height"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Used RAM Memory",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
      }
     ]
    },
    {
     "title": "Used SWAP",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "Used Root FS",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU System Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "CPU System Load (1m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (1 min average)",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Geth Main Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chain Status",
     "type": "gauge",
     "description": "This dashboard provides real-time visibility into the state of the blockchain's head. It tracks the latest block, finalized block, and safe block to monitor synchronization and consensus status. When all three values align, the blockchain is operating smoothly. Discrepancies between these metrics can indicate potential issues with block finalization or synchronization. Use this dashboard to quickly verify the chain's health and ensure that the node stays in sync with the network",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_block{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Head block"
      },
      {
       "expr": "chain_head_finalized{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Head finalized"
      },
      {
       "expr": "chain_head_safe{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Head safe"
      }
     ]
    },
    {
     "title": "Geth Protocol Handshake Errors",
     "type": "timeseries",
     "description": "Displays the count of handshake errors for each protocol type to identify networking issues",
     "gridPos": { "h": 10, "w": 17, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "eth_protocols_eth_egress_handshake_error_forkid{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Handshake Error: Fork ID Mismatch"
      },
      {
       "expr": "eth_protocols_eth_egress_handshake_error_genesis{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Handshake Error: Genesis Block Mismatch"
      },
      {
       "expr": "eth_protocols_eth_egress_handshake_error_network{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Handshake Error: Network Mismatch"
      },
      {
       "expr": "eth_protocols_eth_egress_handshake_error_peer{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Handshake Error: Peer Rejected"
      },
      {
       "expr": "eth_protocols_eth_egress_handshake_error_timeout{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Handshake Error: Timeout"
      },
      {
       "expr": "eth_protocols_eth_egress_handshake_error_version{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Handshake Error: Version Mismatch"
      },
      {
       "expr": "eth_protocols_eth_ingress_handshake_error_forkid{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Handshake Error: Fork ID Mismatch"
      },
      {
       "expr": "eth_protocols_eth_ingress_handshake_error_genesis{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Handshake Error: Genesis Block Mismatch"
      },
      {
       "expr": "eth_protocols_eth_ingress_handshake_error_network{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Handshake Error: Network Mismatch"
      },
      {
       "expr": "eth_protocols_eth_ingress_handshake_error_peer{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Handshake Error: Peer Rejected"
      },
      {
       "expr": "eth_protocols_eth_ingress_handshake_error_timeout{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Handshake Error: Timeout"
      },
      {
       "expr": "eth_protocols_eth_ingress_handshake_error_version{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Handshake Error: Version Mismatch"
      },
      {
       "expr": "eth_protocols_snap_egress_registration_error{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress Registration Error"
      },
      {
       "expr": "eth_protocols_snap_ingress_registration_error{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress Registration Error"
      }
     ]
    },
    {
     "title": "Network Ingress & Egress",
     "type": "bargauge",
     "description": "Tracks the ingress and egress traffic data for monitoring the network performance of the node",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "discover_ingress{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Ingress"
      },
      {
       "expr": "discover_egress{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Geth Transaction Fetcher Performance",
     "type": "heatmap",
     "description": "This dashboard provides an overview of the performance of the transaction fetcher. It tracks the number of transactions announced, queued, requested, and successfully completed. This allows you to monitor the efficiency and responsiveness of the fetcher in handling transactions, helping to identify bottlenecks or delays in the processing pipeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_announces_in{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Transaction Announces In"
      },
      {
       "expr": "eth_fetcher_transaction_queueing_hashes{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Queued Transaction Hashes"
      },
      {
       "expr": "eth_fetcher_transaction_request_out{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Transaction Requests Sent"
      },
      {
       "expr": "eth_fetcher_transaction_request_done{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Completed Transaction Requests"
      }
     ]
    },
    {
     "title": "Geth Transaction and Header Issues Overview",
     "type": "timeseries",
     "description": "This dashboard provides visibility into key transaction and header-related issues that may impact the performance of the node. It tracks underpriced transaction broadcasts, rejected transaction replies, and timeouts during header downloads. The goal is to help identify inefficiencies or problems in the transaction handling and synchronization process, such as price discrepancies or network latency issues",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_broadcasts_underpriced{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Underpriced Transaction Broadcasts"
      },
      {
       "expr": "eth_fetcher_transaction_replies_otherreject{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Rejected Transaction Replies"
      },
      {
       "expr": "eth_downloader_headers_timeout{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Header Download Timeouts"
      }
     ]
    },
    {
     "title": "Geth Node Disk and Memory Usage",
     "type": "timeseries",
     "description": "Displays disk and memory usage for the database, helping you assess resource load",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_size{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Disk usage"
      },
      {
       "expr": "eth_db_chaindata_memory_manualalloc{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Memory usage"
      }
     ]
    },
    {
     "title": "Geth Node Database Reads and Writes",
     "type": "timeseries",
     "description": "Monitoring the number of reads and writes to ancient data, which helps track access to historical information",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_ancient_read{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Chaindata read count"
      },
      {
       "expr": "eth_db_chaindata_ancient_write{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Chaindata write count"
      }
     ]
    },
    {
     "title": "Execution & Inserts Overview",
     "type": "timeseries",
     "description": "This dashboard provides an overview of the node's execution and data insertion performance. It tracks the total number of executed operations and data inserts over time, helping to identify workload patterns, performance bottlenecks, and potential anomalies. Use this dashboard to monitor how efficiently the node processes transactions and manages data growth within the blockchain",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(chain_execution_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)",
       "legendFormat": "Execution Count"
      },
      {
       "expr": "sum(chain_inserts_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)",
       "legendFormat": "Inserts Count"
      }
     ]
    },
    {
     "title": "Storage Reads & Updates",
     "type": "timeseries",
     "description": "This dashboard tracks the frequency of storage read and update operations within the node. It helps monitor storage I/O performance and detect potential bottlenecks. Use this dashboard to analyze how often the node reads from or updates storage, and ensure smooth state transitions without excessive delays caused by disk access",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum(chain_storage_reads_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)\n",
       "legendFormat": "Storage reads Count"
      },
      {
       "expr": "sum(chain_storage_updates_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)\n",
       "legendFormat": "Storage updates Count"
      }
     ]
    },
    {
     "title": "Commits Overview",
     "type": "barchart",
     "description": "This dashboard provides a comprehensive view of commit operations within the node. It displays the number of account commits, snapshot commits, and TrieDB commits over time, segmented by instance. Use this dashboard to monitor the frequency of commit operations, identify patterns, and detect potential bottlenecks that could impact performance. This visualization helps ensure the node processes data efficiently and maintains blockchain consistency across different components",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(chain_account_commits_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)",
       "legendFormat": "Account commits count"
      },
      {
       "expr": "sum(chain_snapshot_commits_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)\n",
       "legendFormat": "Snapshot commits count"
      },
      {
       "expr": "sum(chain_triedb_commits_count{job=~\"$job\",instance=~\"$node:$geth_port\"}) by (instance)\n",
       "legendFormat": "Triedb commits count"
      }
     ]
    },
    {
     "title": "Geth Snap Protocol Sync Lookups Overview",
     "type": "timeseries",
     "description": "This dashboard tracks lookup operations during the node's synchronization process using the Snap protocol. It monitors both internal and external lookups for accounts and storage, helping identify bottlenecks or inefficiencies. The primary use case for this dashboard is during initial synchronization, recovery after a failure, or periodic re-syncs. If high activity is detected outside of these scenarios, it could indicate potential issues such as stuck synchronization or unexpected network behavior\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "eth_protocols_snap_sync_account_lookup_inner{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Inner Account Lookup"
      },
      {
       "expr": "eth_protocols_snap_sync_account_lookup_outer{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Outer Account Lookup"
      },
      {
       "expr": "eth_protocols_snap_sync_storage_lookup_inner{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Inner Storage Lookup"
      },
      {
       "expr": "eth_protocols_snap_sync_storage_lookup_outer{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Outer Storage Lookup"
      }
     ]
    },
    {
     "title": "Blobpool Add Time (Latency Quantiles)",
     "type": "timeseries",
     "description": "This panel shows the time it takes for data to be added to the blobpool, grouped by latency quantiles (0.5, 0.75, 0.95, 0.99, etc.). Monitoring these quantiles provides insights into the distribution and potential outliers in the data processing times",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by (quantile) (blobpool_addtime{job=\"$job\", instance=~\"$node:$geth_port\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blobpool Add Valid Rate",
     "type": "timeseries",
     "description": "This panel tracks the rate at which valid blobs are added to the blobpool in Geth. It helps monitor how frequently the node processes and accepts valid blobs, giving insights into the current activity and throughput of the system. Anomalies or unexpected drops in the rate might indicate network issues, performance degradation, or problems with incoming transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "rate(blobpool_add_valid{job=~\"$job\",instance=~\"$node:$geth_port\"}[5m])",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Geth P2P Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geth P2P Network Connections Overview",
     "type": "timeseries",
     "description": "This dashboard provides a comprehensive view of the node's P2P connections. It monitors the number of connection attempts, successful connections, and connection errors. Additionally, it tracks the ingress and egress network traffic, giving insight into the overall network activity and potential connectivity issues. Use this dashboard to identify network bottlenecks and ensure smooth communication between nodes in the network.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "p2p_dials{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Connection Attempts"
      },
      {
       "expr": "p2p_dials_success{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Successful Connections"
      },
      {
       "expr": "p2p_dials_error_connection{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Connection Errors"
      }
     ]
    },
    {
     "title": "Geth P2P Traffic Overview",
     "type": "timeseries",
     "description": "This dashboard displays the real-time speed of incoming (ingress) and outgoing (egress) P2P traffic. It helps monitor the bandwidth usage by showing the amount of data transferred per second. This is essential for understanding the node’s current network activity, detecting potential bottlenecks, and ensuring the node maintains stable communication with peers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(p2p_ingress{job=~\"$job\",instance=~\"$node:$geth_port\"}[5m])",
       "legendFormat": "Ingress Traffic"
      },
      {
       "expr": "rate(p2p_egress{job=~\"$job\",instance=~\"$node:$geth_port\"}[5m])\n",
       "legendFormat": "Egress Traffic"
      }
     ]
    },
    {
     "title": "Geth TxPool Health Overview",
     "type": "timeseries",
     "description": "Monitors the overall state of the transaction pool, including the number of valid and invalid transactions, queued transactions, and pending transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "txpool_valid{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Valid Transactions"
      },
      {
       "expr": "txpool_invalid{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Invalid Transactions"
      },
      {
       "expr": "txpool_pending{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Pending Transactions"
      },
      {
       "expr": "txpool_queued{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Queued Transactions"
      }
     ]
    },
    {
     "title": "Geth TxPool Throttling and Overflow",
     "type": "timeseries",
     "description": "This dashboard monitors how frequently transactions are throttled, overflowed, or rejected due to insufficient gas price, helping to identify performance bottlenecks in the transaction pool.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "txpool_throttle{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Throttled Transactions"
      },
      {
       "expr": "txpool_overflowed{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Overflowed Transactions"
      },
      {
       "expr": "txpool_underpriced{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "Underpriced Transactions"
      }
     ]
    },
    {
     "title": "RPC Request Success and Failure Overview",
     "type": "timeseries",
     "description": "This dashboard monitors the number of successful and failed RPC requests over time. It helps identify issues in communication and provides insights into the stability of RPC operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rpc_failure{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "RPC failure"
      },
      {
       "expr": "rpc_success{job=~\"$job\",instance=~\"$node:$geth_port\"}",
       "legendFormat": "RPC success"
      }
     ]
    },
    {
     "title": "RPC Request Duration Overview",
     "type": "timeseries",
     "description": "This dashboard tracks the duration of all RPC requests to monitor performance. It uses quantiles to display the median (50th percentile), upper quartiles, and outliers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_all{quantile=\"0.5\",job=~\"$job\",instance=~\"$node:$geth_port\"}/ 1e6",
       "legendFormat": "quantile=\"0.5\""
      },
      {
       "expr": "rpc_duration_all{quantile=\"0.75\",job=~\"$job\",instance=~\"$node:$geth_port\"}/ 1e6",
       "legendFormat": "quantile=\"0.75\""
      },
      {
       "expr": "rpc_duration_all{quantile=\"0.95\",job=~\"$job\",instance=~\"$node:$geth_port\"} / 1e6",
       "legendFormat": "quantile=\"0.95\""
      },
      {
       "expr": "rpc_duration_all{quantile=\"0.99\",job=~\"$job\",instance=~\"$node:$geth_port\"} / 1e6",
       "legendFormat": "quantile=\"0.99\""
      }
     ]
    },
    {
     "title": "Geth getLogs RPC Performance",
     "type": "timeseries",
     "description": "This dashboard monitors the performance of the eth_getLogs RPC method to identify if fetching logs is causing delays",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_eth_getLogs_success{quantile=\"0.5\",job=~\"$job\",instance=~\"$node:$geth_port\"}/ 1e6",
       "legendFormat": "Median (50th Percentile)"
      },
      {
       "expr": "rpc_duration_eth_getLogs_success{quantile=\"0.75\",job=~\"$job\",instance=~\"$node:$geth_port\"}/ 1e6",
       "legendFormat": "75th Percentile"
      },
      {
       "expr": "rpc_duration_eth_getLogs_success{quantile=\"0.95\",job=~\"$job\",instance=~\"$node:$geth_port\"}/ 1e6",
       "legendFormat": "95th Percentile"
      }
     ]
    },
    {
     "title": "Geth ForkchoiceUpdatedV3 RPC Performance",
     "type": "timeseries",
     "description": "This dashboard tracks the execution duration of forkchoiceUpdatedV3 RPC calls. It provides insights into the time taken to complete these requests by displaying different quantiles, such as the median (50th percentile), 75th percentile, and 95th percentile. Monitoring these metrics helps identify performance bottlenecks and unusual delays, ensuring that the RPC service operates efficiently.\n\nUse this dashboard to detect potential slowdowns in forkchoiceUpdatedV3 calls and analyze patterns over time to maintain smooth operation of the node's consensus updates",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=\"0.5\",job=~\"$job\",instance=~\"$node:$geth_port\"} / 1e6",
       "legendFormat": "Median (50th Percentile)"
      },
      {
       "expr": "rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=\"0.75\",job=~\"$job\",instance=~\"$node:$geth_port\"} / 1e6",
       "legendFormat": "75th Percentile"
      },
      {
       "expr": "rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=\"0.95\",job=~\"$job\",instance=~\"$node:$geth_port\"} / 1e6",
       "legendFormat": "95th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Staking Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Staking Delegation Metrics",
     "type": "stat",
     "description": "This dashboard provides insights into the total number of staking delegations within the ecosystem. It tracks the cosmos_staking_delegate counter, enabling users to monitor the activity and growth of staking within the network.\n\nReal-time updates help operators understand delegation trends and make informed decisions regarding staking strategies.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_staking_delegate{job=\"$job\", instance=\"$node:$story_port\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EvM Staking Queue Depth",
     "type": "stat",
     "description": "This dashboard provides real-time insights into the queue depth of the EvM staking module, displaying the current number of pending tasks. Monitoring queue depth helps identify potential bottlenecks in processing and ensures efficient operation. Alerts can be set up to notify operators when the queue exceeds predefined thresholds, facilitating proactive performance management",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "evmstaking_queue_depth{job=\"$job\", instance=\"$node:$story_port\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Staking Undelegation Metrics",
     "type": "stat",
     "description": "This dashboard provides insights into the total number of staking undelegations within the ecosystem. It tracks the cosmos_staking_undelegate counter, allowing users to monitor the activity and trends in undelegation.\n\nReal-time updates help operators understand the dynamics of staking and make informed decisions regarding their strategies",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_staking_undelegate{job=\"$job\", instance=\"$node:$story_port\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Minted Tokens",
     "type": "timeseries",
     "description": "provides insights into the total number of minted tokens within the ecosystem. It tracks the cosmos_minted_tokens gauge, enabling users to monitor the current token supply and analyze inflation trends over time",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "cosmos_minted_tokens{job=\"$job\", instance=\"$node:$story_port\"}",
       "legendFormat": "Total Minted Tokens"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Transaction Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Block Processing Time",
     "type": "timeseries",
     "description": "This dashboard shows the average time spent processing blocks over the last 5 minutes, helping to monitor the efficiency of block finalization",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(cometbft_state_block_processing_time_sum{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m])) / sum(rate(cometbft_state_block_processing_time_count{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
       "legendFormat": "Average Block Processing Time"
      }
     ]
    },
    {
     "title": "Proposal Receive Rate",
     "type": "timeseries",
     "description": "Tracks the rate at which the node receives block proposals over a given interval. This metric helps monitor the node's participation in the consensus process. A steady rate indicates healthy network activity, while drops may suggest connectivity issues or synchronization problems. Spikes in the rate can indicate unusual network behavior. Monitoring this metric is essential for ensuring smooth block propagation and stable consensus operations",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(cometbft_consensus_proposal_receive_count{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}[$__rate_interval])",
       "legendFormat": "Block Time"
      }
     ]
    },
    {
     "title": "Block Size (Bytes)",
     "type": "timeseries",
     "description": "Shows the data size of the block in bytes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "cometbft_consensus_block_size_bytes{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "Block Size"
      }
     ]
    },
    {
     "title": "Block Processing Time Distribution",
     "type": "timeseries",
     "description": "This dashboard monitors the +Inf bucket for block processing time, which indicates the total count of blocks processed beyond all other thresholds",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(cometbft_state_block_processing_time_bucket{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\", le=\"+Inf\"}[5m]))",
       "legendFormat": "<= +Inf sec"
      }
     ]
    },
    {
     "title": "Mempool Size (Bytes)",
     "type": "gauge",
     "description": "Measures the total size of the mempool in bytes. This metric helps monitor memory consumption and can provide insights into the amount of transaction data awaiting inclusion in the blockchain",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_mempool_size_bytes{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Transactions",
     "type": "timeseries",
     "description": "Tracks the total number of transactions processed by the node across all blocks in the chain. This metric provides insight into the overall network activity and throughput. A higher value indicates increased usage and transaction flow, while sudden drops may signal potential network issues or reduced participation. Monitoring this metric helps ensure the health and performance of the blockchain",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cometbft_consensus_total_txs{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "Total TXs"
      }
     ]
    },
    {
     "title": "Mempool Active Outbound Connections",
     "type": "timeseries",
     "description": "Tracks the number of active outbound connections used for gossiping transactions. This metric helps monitor the networking behavior and ensures that the node effectively propagates transactions across the network",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cometbft_mempool_active_outbound_connections{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "Mempool Size"
      }
     ]
    },
    {
     "title": "Mempool Size(Number of Transactions)",
     "type": "gauge",
     "description": "Represents the number of uncommitted transactions currently held in the mempool. A growing size may indicate high network activity or delays in block production, while an empty mempool suggests low transaction flow",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cometbft_mempool_size{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}",
       "legendFormat": "{{_name_}}"
      }
     ]
    },
    {
     "title": "Block Processing Performance Dashboard",
     "type": "timeseries",
     "description": "This dashboard offers insights into block processing performance across key modules in the Cosmos ecosystem, including evmstaking, gov, and staking. It displays average processing times, allowing users to identify bottlenecks and optimize efficiency.\n\nReal-time updates ensure operators have the latest performance data to maintain optimal operation within the Cosmos network",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(cosmos_end_blocker_sum{module=\"evmstaking\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m])) / sum(rate(cosmos_end_blocker_count{module=\"evmstaking\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
       "legendFormat": "Average Block Processing Time (evmstaking)"
      },
      {
       "expr": "sum(rate(cosmos_end_blocker_sum{module=\"gov\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m])) / sum(rate(cosmos_end_blocker_count{module=\"gov\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
       "legendFormat": "Average Block Processing Time (gov)"
      },
      {
       "expr": "sum(rate(cosmos_end_blocker_sum{module=\"staking\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m])) / sum(rate(cosmos_end_blocker_count{module=\"staking\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
       "legendFormat": "Average Block Processing Time (staking)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node P2P Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Bytes per Second (Total)",
   "type": "timeseries",
   "description": "shows the total rate of incoming P2P messages in bytes. It aggregates all message types to provide a holistic view of network traffic. This metric is useful for monitoring the overall communication load on the node, helping to identify patterns of network usage, potential congestion, or anomalies in message flow. A consistent rate indicates stable network operations, while sudden changes may require further investigation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_message_receive_bytes_total{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
     "legendFormat": "Received B/s"
    }
   ]
  },
  {
   "title": "Sent Bytes per Second (Total)",
   "type": "timeseries",
   "description": "shows the total rate of outgoing P2P messages in bytes. It aggregates all message types to provide an overview of the outbound network traffic. Monitoring this metric helps track how actively the node communicates with peers and ensures smooth message propagation. Sudden spikes may indicate high network activity, while drops could point to connectivity issues or node performance problems",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(cometbft_p2p_message_send_bytes_total{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
     "legendFormat": "Sent B/s"
    }
   ]
  },
  {
   "title": "P2P Message Receive Rate by Message Type",
   "type": "timeseries",
   "description": "Displays the rate of incoming P2P messages in bytes per second, grouped by message type. It helps monitor the volume and types of messages exchanged over the network, providing insights into the network's communication patterns and load. A steady flow of messages indicates healthy network activity, while irregular patterns or spikes can signal potential issues such as network congestion or unexpected behavior",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (message_type) (rate(cometbft_p2p_message_receive_bytes_total{chain_id=\"iliad-0\", job=~\"$job\",instance=~\"$node:$story_port\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Disk Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Go Runtime and Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Process CPU and Memory Usage",
   "type": "timeseries",
   "description": "Monitoring both CPU and memory together gives a comprehensive view of the node’s performance and helps detect potential bottlenecks or resource exhaustion issues. It allows for early identification of performance degradation, ensuring the node remains responsive and stable",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$node:$story_port\"}[1m])) * 100",
     "legendFormat": "CPU Usage (%)"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"$job\",instance=~\"$node:$story_port\"})",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Go Memory Statistics",
   "type": "timeseries",
   "description": "Shows key metrics for Go runtime memory usage:\n- Allocated Memory: Total memory currently in use.\n- Heap Allocated: Memory allocated on the heap.\n- Heap In-Use: Actively used heap memory.\n\nHelps monitor memory efficiency, detect leaks, and ensure stable performance.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=~\"$job\",instance=~\"$node:$story_port\"})",
     "legendFormat": "Allocated Memory"
    },
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=~\"$job\",instance=~\"$node:$story_port\"})",
     "legendFormat": "Heap Allocated"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\",instance=~\"$node:$story_port\"})",
     "legendFormat": "Heap In Use"
    }
   ]
  },
  {
   "title": "Garbage Collection and Goroutines",
   "type": "timeseries",
   "description": "Tracks Go runtime metrics related to garbage collection (GC) and goroutines:\n- GC Pause Duration:\nDisplays the average time (in seconds) spent on garbage collection pauses over a 5-minute interval, giving insights into the GC impact on application performance.\n\n- Goroutines:\nShows the number of active goroutines over time, helping monitor concurrency and workload within the application.\n\nThese metrics are essential for understanding the behavior of the Go runtime, identifying performance bottlenecks, and ensuring efficient memory management",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"$job\",instance=~\"$node:$story_port\"}[5m])) / sum(rate(go_gc_duration_seconds_count{job=~\"$job\",instance=~\"$node:$story_port\"}[5m]))",
     "legendFormat": "GC Pause Duration"
    },
    {
     "expr": "sum(go_goroutines{job=~\"$job\",instance=~\"$node:$story_port\"})",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Using file descriptors (%)",
   "type": "timeseries",
   "description": "This panel displays the percentage of file descriptors currently in use by the process:\nMonitoring this metric helps ensure the application is not approaching file descriptor limits, which could lead to resource exhaustion and service disruptions. A high percentage may indicate the need to optimize resource usage or increase system limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(process_open_fds{job=~\"$job\",instance=~\"$node:$story_port\"}) / sum(process_max_fds{job=~\"$job\",instance=~\"$node:$story_port\"})) * 100",
     "legendFormat": "Open FDs"
    }
   ]
  }
 ]
}